In [4]:
#importamos las librerias pandas y numpy para poder realizar la limpieza de datos

import pandas as pd
import numpy as np

1. EXPLORACION DE DATOS

In [2]:
# cargamos la base a trabajar
from google.colab import files
uploaded =files.upload()

Saving ventas_sucias_5000.csv to ventas_sucias_5000.csv

In [5]:
#nombramos el archivo
vc= pd.read_csv('ventas_sucias_5000.csv')

In [7]:
#generamos una copia en la cual se va a trabajar

vc1= vc.copy()

In [8]:
vc1.head()

  cliente producto  precio cantidad      pais    metodo_pago             fecha
0   Maria  Monitor  1326.0      NaN      peru       Efectivo  01/01/2024 00:00
1   Luisa   Laptop    55.0        2     chile        Tarjeta  01/01/2024 01:00
2  Carlos  Monitor  1203.0        9  Colombia       Efectivo  01/01/2024 02:00
3   Luisa  Monitor  1304.0        3      Perú  TRANSFERENCIA  01/01/2024 03:00
4   Luisa  Monitor   426.0        6     chile        Tarjeta  01/01/2024 04:00

In [9]:
vc1.info()

#verificar informacion

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   cliente      5000 non-null   object
 1   producto     5000 non-null   object
 2   precio       4950 non-null   float64
 3   cantidad     4950 non-null   object
 4   pais         5000 non-null   object
 5   metodo_pago  5000 non-null   object
 6   fecha        5000 non-null   object
dtypes: float64(1), object(6)
memory usage: 273.6+ KB

In [10]:
#verificamos cuantas filas ycolumnas
#muestra 5000 filas y 7 columnas
vc1.shape

(5000, 7)

In [11]:
#verificamos la informacion
vc1.describe (include="all")

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
count,5000,5000,4950.000000,4950,5000,5000,5000
unique,6,5,NaN,10,7,4,4825
top,Ana,Mouse,NaN,2,chile,TRANSFERENCIA,19/01/2024 00:00
freq,870,1069,NaN,573,733,1276,5
mean,NaN,NaN,5053.823434,NaN,NaN,NaN,NaN
std,NaN,NaN,63379.982009,NaN,NaN,NaN,NaN
min,NaN,NaN,10.000000,NaN,NaN,NaN,NaN
25%,NaN,NaN,531.000000,NaN,NaN,NaN,NaN
50%,NaN,NaN,1027.000000,NaN,NaN,NaN,NaN
75%,NaN,NaN,1519.000000,NaN,NaN,NaN,NaN
max,NaN,NaN,999999.000000,NaN,NaN,NaN,NaN

In [12]:
#verificar datos faltantes
vc1.isnull().sum()
#muestra que en la columna de precio y cantidad hacen falta 50 datos

cliente         0
producto        0
precio         50
cantidad       50
pais            0
metodo_pago     0
fecha           0
dtype: int64

In [13]:
#verificar duplicados

vc1.duplicated().sum()

#no se observan dato duplicados

np.int64(0)

se puede observar que contiene 5000 filas y 7 columnas
cuenta con datos inconsistentes
no se observan duplicados
hay 2 columnas las cuales les falta 50 valores a cada una

2.LIMPIEZA DE DATOS PANDAS

In [14]:
# manejo de nulos
vc1["precio"] = vc1["precio"].fillna("desconocido")
vc1["cliente"] = vc1["cliente"].fillna("desconocido")
vc1["producto"] = vc1["producto"].fillna("desconocido")
vc1["cantidad"] = vc1["cantidad"].fillna("desconocido")
vc1["pais"] = vc1["pais"].fillna("desconocido")
vc1["metodo_pago"] = vc1["metodo_pago"].fillna("desconocido")
vc1["fecha"] = vc1["fecha"].fillna("desconocido")

In [15]:
#Convertir vacios
vc1 ["precio"] = vc1["precio"].replace("",None)
vc1 ["precio"] = vc1["precio"].replace(" ",None)

vc1 ["cliente"] = vc1["cliente"].replace("",None)
vc1 ["cliente"] = vc1["cliente"].replace(" ",None)

vc1 ["producto"] = vc1["producto"].replace("",None)
vc1 ["producto"] = vc1["producto"].replace(" ",None)

vc1 ["cantidad"] = vc1["cantidad"].replace("",None)
vc1 ["cantidad"] = vc1["cantidad"].replace(" ",None)

vc1 ["pais"] = vc1["pais"].replace("",None)
vc1 ["pais"] = vc1["pais"].replace(" ",None)

vc1 ["metodo_pago"] = vc1["metodo_pago"].replace("",None)
vc1 ["metodo_pago"] = vc1["metodo_pago"].replace(" ",None)

vc1 ["fecha"] = vc1["fecha"].replace("",None)
vc1 ["fecha"] = vc1["fecha"].replace(" ",None)

In [16]:
#Mapeo
vc1["pais"] = vc1["pais"].replace({
    "COL":"colombia",
    "col": "colombia",
    "Colombia" :"colombia",
    "Chile": "chile",
    "Perú" : "peru"
    })

In [17]:
#formato de fecha
vc1['fecha'] = pd.to_datetime(vc1['fecha'], errors='coerce', format='mixed', dayfirst=True)

In [18]:
#convertir la columna a numerica
vc1["precio"]=pd.to_numeric(vc1["precio"], errors="coerce")

In [19]:
vc1["precio"].dtype

dtype('float64')

In [20]:
# Manejo de outliers

vc1 = vc1[vc1["precio"]<100000]

In [21]:
vc1.head()

,cliente,producto,precio,cantidad,pais,metodo_pago,fecha
0,Maria,Monitor,1326.0,desconocido,peru,Efectivo,2024-01-01 00:00:00
1,Luisa,Laptop,55.0,2,chile,Tarjeta,2024-01-01 01:00:00
2,Carlos,Monitor,1203.0,9,colombia,Efectivo,2024-01-01 02:00:00
3,Luisa,Monitor,1304.0,3,peru,TRANSFERENCIA,2024-01-01 03:00:00
4,Luisa,Monitor,426.0,6,chile,Tarjeta,2024-01-01 04:00:00

en esta parte se realizo limpieza de datos corrigiendo vacios, estandarizando formato de fecha y dejando valores consistentes
se debieron eliminar algunos daatos debido a que no eran concordes a la informacion y representaba datos inexactos

3. ANALISIS CON PANDAS

In [22]:
# convcertir columnas en formato numerico para poder solucionar diferentes variables
vc1["cantidad"]= pd.to_numeric(vc1['cantidad'],errors="coerce")

In [23]:
#eliminar datos Nan

vc1= vc1.dropna(subset=["cantidad"])

In [24]:
# total vendido
vc1["Total"]=vc1["precio"]*vc1["cantidad"]

vc1["Total"].sum()

np.float64(24328023.0)

In [25]:
#promedio de ventas
vc1["Total"].mean()

np.float64(5033.731222842955)

In [26]:
#venta maxima
vc1["Total"].max()

17955.0

In [27]:
#venta minima
vc1["Total"].min()

10.0

In [28]:
#promedio con numpy
np.nanmean(vc1["Total"])

np.float64(5033.731222842955)

In [29]:
Ventas = vc1[['precio','cantidad']].to_numpy()

precios = Ventas[:,0]
cantidades = Ventas[:,1]

Total_ventas = precios * cantidades
print(Total_ventas)

print("Promedio ventas: ",np.mean(Total_ventas))
print("Ventas mayores a 1000: ", len(Total_ventas[Total_ventas>1000]))

[  110. 10827.  3912. ...  3552. 10928.   406.]
Promedio ventas:  5033.731222842955
Ventas mayores a 1000:  4097

In [31]:
# producto con mas ventas
vc1.groupby("producto")["Total"].sum().sort_values(ascending=False)

producto
Mouse      5267067.0
Laptop     4910898.0
Monitor    4805955.0
Celular    4755777.0
Teclado    4588326.0
Name: Total, dtype: float64

In [32]:
#pais con mas ventas
vc1.groupby("pais")["Total"].sum().sort_values(ascending=False)

pais
colombia    10520899.0
chile        6994648.0
peru         6812476.0
Name: Total, dtype: float64

aqui se puede observar que el pais con mas ventas es Colombia
el top 5 de productos mas vendidos queda de la siguiente manera:
1 Mouse
2.Laptop
3.Monitor
4.Celular
5.Teclado

4.INTRODUCCION A NUMPY

In [33]:
#Convertir columnas numéricas a un array
data = vc1[['precio', 'cantidad','Total']].to_numpy()

In [34]:
#separar columnas
precios = data[:, 0]
cantidades = data[:, 1]
Total= data[:,2]

In [38]:
#vectorizar para calcular las ventas
ventas_totales = precios * cantidades
print(ventas_totales)

[  110. 10827.  3912. ...  3552. 10928.   406.]

5.ANALISIS CON NUMPY

In [36]:
#suma total de ventas
total_ventas=np.sum(ventas_totales)
print(total_ventas)

24328023.0

In [39]:
#promedio de ventas
promedio_ventas=np.mean(ventas_totales)
print(promedio_ventas)

5033.731222842955

In [40]:
#venta maxima
venta_maxima=np.max(ventas_totales)
print(venta_maxima)

17955.0

In [41]:
#venta minima
venta_minima=np.min(ventas_totales)
print(venta_minima)

10.0

In [44]:
#cantidad de venta superiores a 1000
ventas_mayores_1000=np.sum(ventas_totales>1000)
print(ventas_mayores_1000)

4097

¿Qué ventajas observas al usar NumPy?
es mas facil realizarla funcion es decir es un enlace directo para lo que seb requiere porque ya esta establecida mientras que python debemos indicarle que debe hacer
¿Qué significa “vectorización”?
es una forma de realizar operaciones matematicas sobre muchos datos al mismo tiempo sin tener que usar como ciclos para porder realizarlos
¿Qué hace la expresión data[:, 0]?
introoducir antes de la posicion señalada

6. — INTERPRETACION DE RESULTADOS
Analiza y responde:
¿Los resultados obtenidos tienen sentido?
No, hay valores como precio que no concuerdan a la realidad de una empresa que necesita un analisis de datos para toma de decisiones
¿Detectaste valores sospechosos?
varios, precios y cantidades que no eran coherentes asi como ninguna fecha de metodo de pago para sostener un control
¿El promedio representa correctamente los datos?
no es un valor exacto por lo cual para el ejercicio es el valor como resultado pero en un analisis real representaria un error
¿Qué decisiones tomarías si esta fuera información real de negocio?
primero calidad del dato a la hora de diligenciar el formato, asi mismo coherencia e inventario para poder ver representado la realidad y tomar decisiones